import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ConvexClientProvider } from "./ConvexClientProvider";

import { GlobalProvider } from "@/context/globalContext";
import { EmojiProvider } from "@/context/EmojiContext";
import { ConvexQueryCacheProvider } from "convex-helpers/react/cache/provider";
import { VoiceRecorderProvider } from "@/context/audio-context";
import { Toaster } from "@/components/ui/sonner";
// import { ChatSeenProvider } from "../context/chatSeenContext";
// import { Monitoring } from "react-scan/monitoring/next"; // Import this first before React
// import { ReactScan } from "@/components/react-scan";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "chat App bale Like",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en" suppressHydrationWarning>
        <body className="">
          <ConvexClientProvider>
            <GlobalProvider>
              <EmojiProvider>
                <VoiceRecorderProvider>
                  <ConvexQueryCacheProvider>
                    {/* <div className="w-full max-w-[2400px] isolate mx-auto flex h-dvh  overflow-hidden"> */}
                    {children}
                    <Toaster />
                    {/* </div> */}
                  </ConvexQueryCacheProvider>
                </VoiceRecorderProvider>
              </EmojiProvider>
            </GlobalProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
